### ISSUE TITLE
Using get_template_directory

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/shop-isle#100]
We should use get_stylesheet_directory instead of get_template_directory in this theme to make it child theme friendly. Same goes for lite.

@rodica-andronache

**Comment by ineagu** [comment]
@rodica-andronache can you take a look at this and see what we can improve ? for all 3 repos

**Comment by rodica-andronache** [comment]
From what I know, we should use get_stylesheet_directory only for the files that should be able to to be  overridden in a child theme.  get_template_directory  for those files that should not be changed from the child theme, and get_template_part for including theme parts.

It should be tested well. I know there are users complaining that a child theme is not easy to create/customize

**Comment by HardeepAsrani** [comment]
We should be using get_template_directory. Few months back I had a theme with get_stylesheet_directory. As it turns out, if you don't have a white in your child theme it didn't look for it in the parent theme. Lesson learned. :)
