### ISSUE TITLE
Customizing Slider section issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/shop-isle#122]
@rodica-andronache We have a bug in Slider section. When I want to change a field on the slide, the mouse automatically moves up at "upload image". I attached a short video with the problem. 

https://www.dropbox.com/s/ea16pmwumppp8hs/Slider%20Section%20issue.mov?dl=0

I was able to change the fields using "Tab".

**Comment by rodica-andronache** [comment]
only on mac

**Comment by ineagu** [comment]
Can you investigate this ? it was affected by the new slider ?
