### ISSUE TITLE
Increase font overall by 2px

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/shop-isle#127]
@claudiuvertistudio I think we can try to increase the font overall a little bit ( or where it makes sense ) and see how it works

**Comment by rodica-andronache** [comment]
@ineagu can we close this?

**Comment by ineagu** [comment]
why close ?

On Mon, Apr 18, 2016 at 3:01 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> Assigned #127 <https://github.com/Codeinwp/shop-isle/issues/127> to
> @ineagu <https://github.com/ineagu>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/127#event-631186855>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by ineagu** [comment]
why haven't we done it and why do you wanted to close ? :D I think a lot of people want this, also read this : https://wordpress.org/support/topic/changing-the-font-size-for-the-body-of-each-page-using-the-shopisle-free-theme?replies=2

**Comment by claudiuvertistudio** [comment]
@ineagu  I have read the comments and I haven't seen anything like ".font_7" in our css. I think that is a good idea to increase the font with 2px but we can add a option in customizer to change the font size of body if the users want this, maybe a dropdown with some values ( 12, 13, 14, 15, 16). What do you think?

**Comment by ineagu** [comment]
yep, we can do it.

However by default we can change it to 13, looks like is the best option.
After that if they want they can go back to 12, or increase even further.

On Wed, May 11, 2016 at 2:29 PM, Claudiu Buruiana <notifications@github.com>
wrote:

> @ineagu <https://github.com/ineagu> I have read the comments and I
> haven't seen anything like ".font_7" in our css. I think that is a good
> idea to increase the font with 2px but we can add a option in customizer to
> change the font size of body if the users want this, maybe a dropdown with
> some values ( 12, 13, 14, 15, 16). What do you think?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/127#issuecomment-218444846>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by claudiuvertistudio** [comment]
@ineagu can you take a look?

**Comment by ineagu** [comment]
looks good, I have also added this testing post :
http://dev2.themeisle.com/shop-isle/2016/05/12/test/

On Thu, May 12, 2016 at 2:57 PM, Claudiu Buruiana <notifications@github.com>
wrote:

> @ineagu <https://github.com/ineagu> can you take a look?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/127#issuecomment-218748796>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
@claudiuvertistudio shouldn't the font for the navigation menu change? I tried and it doesn't seam to work

**Comment by ineagu** [comment]
not really, I think the current menu looks good, Do you think is too small ?

**Comment by claudiuvertistudio** [comment]
the font size of navigation doesn't change, I thought it looked good witn 11px. 
@ineagu if you think it is too small I could increase it to 12px.

**Comment by ineagu** [comment]
for me the menu font looks ok I think

On Wed, May 18, 2016 at 8:55 AM, Claudiu Buruiana <notifications@github.com>
wrote:

> the font size of navigation doesn't change, I thought it looked good witn
> 11px.
> @ineagu <https://github.com/ineagu> if you think it is too small I could
> increase it to 12px.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/127#issuecomment-219941250>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
