### ISSUE TITLE
Add a Language switcher on demo

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/shop-isle#133]

**Comment by rodica-andronache** [comment]
It's not appearing in the menu 
http://prntscr.com/a4uj3k

**Comment by rodica-andronache** [comment]
@ineagu I added polylang on dev2, and I was thinking that maybe i can clone everything from demo here and @mileamadalin or someone else , could try to translate everything on dev2, to see if there are remaining issues/sections that can't be translated. And if everything is ok, we can then copy everything on demo.What do you think?

**Comment by ineagu** [comment]
the position and image quality of the flags is a bit awful, so we first
need to solve this. 2nd for french I think we have the translation.

On Thu, Mar 24, 2016 at 1:17 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> I added polylang on dev2, and I was
> thinking that maybe i can clone everything from demo here and
> @mileamadalin <https://github.com/mileamadalin> or someone else , could
> try to translate everything on dev2, to see if there are remaining
> issues/sections that can't be translated. And if everything is ok, we can
> then copy everything on demo.What do you think?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/133#issuecomment-200807486>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by ineagu** [comment]
@rodica-andronache I think here we have found a good way to do it, any updates ?

**Comment by rodica-andronache** [comment]
yes, but we first need to fix this https://github.com/Codeinwp/shop-isle/issues/159 and check the theme, is everything is working well and can be translated
