### ISSUE TITLE
Better options for products

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/shop-isle#145]
Source: Forum

> Hi,
> 
> I’m in the process of customising and tweaking the ShopIsle theme on localhost. Everything is working well, and it’s perfect for my needs – thank you!
> 
> The only problem I’m having is finding where to take out the “Add to Cart” button that hovers over the Catalogue images on the Home Page, Shop Page, and Catalogue Pages. Ideally I would like to replace this with a “See more” feature, which will redirect to the single product page.
> 
> It would function in a similar way to the hover that appears when a product has variations. These products automatically have the “add to cart” button replaced with “Product Options”, which links to the single product page.

@rodica-andronache

**Comment by HardeepAsrani** [comment]
@ineagu What do you think? Makes a lot of sense to me. :)

**Comment by ineagu** [comment]
It makes sense, however this is not an option that I would add. I believe that the current solution is the best for most of the people.

In specific cases people can hire developers to customize the theme. For example the simplest way can be to put display none on the button, or a bit more advanced to do some changes in a child theme.
