### ISSUE TITLE
Add_image_size for all images

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/shop-isle#15]

**Comment by ineagu** [comment]
have we done that ?

**Comment by ineagu** [comment]
@rodica-andronache updates here ? what is the current situation with image_size ?

**Comment by rodica-andronache** [comment]
from what I see we only have 3 image sizes. I think maybe we should check all the images used in the theme and see if we need more.  I think so

**Comment by ineagu** [comment]
ok, let's try to have a proper look at all shop-isle issues and see what we
can do .

On Thu, May 12, 2016 at 6:22 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> from what I see we only have 3 image sizes. I think maybe we should check
> all the images used in the theme and see if we need more. I think so
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/15#issuecomment-218809732>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
