### ISSUE TITLE
WooCommerce compare list

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/shop-isle#156]
@rodica-andronache looks like we have a bug here. When I press the "Compare" button, nothing happens.

<img width="1212" alt="skitch 3" src="https://cloud.githubusercontent.com/assets/6906834/13552329/8a59aa22-e31b-11e5-8241-cf21bfaf2a68.png">

It's just me?

**Comment by rodica-andronache** [comment]
@mileamadalin have you tried this on demo? Because http://prnt.sc/ac80pc it was selected the shop page, and it shouldn't be this way. I created a page called Compare (with full width template) and selected this one. 
For me it's working ok, could you please check again?

**Comment by mileamadalin** [comment]
@rodica-andronache Yes, now everything is ok. Thank you!
