### ISSUE TITLE
Translation ready for repeater

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/shop-isle#159]

**Comment by ineagu** [comment]
@rodica-andronache do you have more details here ? what exactly isn't working, since we already have 3 repos to manage now, better to fix everything asap.

**Comment by rodica-andronache** [comment]
we need to add/update the code for the repeater used in the theme. Slider section, banner section, shortcode section etc

**Comment by ineagu** [comment]
just cristi can do that ?

On Thu, May 12, 2016 at 6:23 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> we need to add/update the code for the repeater used in the theme. Slider
> section, banner section, shortcode section etc
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/159#issuecomment-218810223>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
he can probably do it the fastest
