### ISSUE TITLE
Recommend WooCommerce and InterGeo Maps when activating theme

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/shop-isle#161]
Source: http://wplift.com/shopisle-free-woocommerce-theme

I did also notice, on theme activation it only recommended one plugin – it should also recommend the WooCommerce plugin itself and also the Intergeo map plugin and Contact Form 7 as the theme directly integrates with both of these.

**Comment by ineagu** [comment]
I do not agree with that, we can however recommend woocommerce, but not intergeo
