### ISSUE TITLE
Issue with WooThemes Helper plugin

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/shop-isle#166]
More details: http://themeisle.com/forums/topic/slider-banner-un-editable/

@rodica-andronache

**Comment by ineagu** [comment]
aici din ce imi dau seama pare ca noi folosim niste filtre standard la care se face override ceva

**Comment by ineagu** [comment]
@claudiuvertistudio ai gasit ce ar putea sa fie aici ? Cred ca trebuie rezolvat, pare ca se cam plange lumea.

**Comment by ineagu** [comment]
Daca nu iti dai seama il poti muta Rodicai

**Comment by claudiuvertistudio** [comment]
am instalat WooThemes Helper, cateva plugin-uri free de la woothemes dar pare sa mearga ok site-ul si customizer-ul. @rodica-andronache poti sa mai testezi si tu odata?

**Comment by rodica-andronache** [comment]
Da, si eu am testat si pare sa mearga. Cred ca ar fi trebuit mai multe detalii de la inceput, cand a vb cu clientul si testat atunci de hardeep dar acum deja au trecut 2 luni nu stiu daca mai e ok sa-l intrebe din nou, avand in vedere ca parea multumit la final clientul.

@ineagu sa inchid issue-ul asta, si sa-i zic in particular lui hardeep ca ar fi trebuit mai multe detalii?

**Comment by ineagu** [comment]
cred ca poti inchide

2016-05-17 16:47 GMT+02:00 Rodica-Elena Andronache <notifications@github.com
>:

> Da, si eu am testat si pare sa mearga. Cred ca ar fi trebuit mai multe
> detalii de la inceput, cand a vb cu clientul si testat atunci de hardeep
> dar acum deja au trecut 2 luni nu stiu daca mai e ok sa-l intrebe din nou,
> avand in vedere ca parea multumit la final clientul.
>
> @ineagu <https://github.com/ineagu> sa inchid issue-ul asta, si sa-i zic
> in particular lui hardeep ca ar fi trebuit mai multe detalii?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/166#issuecomment-219741275>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
