### ISSUE TITLE
New screenshot

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/shop-isle#167]

**Comment by abaicus** [comment]
@ineagu Mai e valabil issue-ul asta?

**Comment by ineagu** [comment]
Cred ca da, nu stiu cum arata screenshot curent, daca e foarte ok, lasam asa

**Comment by rodica-andronache** [comment]
@ineagu asa arata https://github.com/Codeinwp/shop-isle/blob/production/screenshot.png

**Comment by ineagu** [comment]
cred ca am putea avea ceva mai colorat putin si text mai fain pe acolo

On Wed, Apr 20, 2016 at 1:48 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> asa arata
> https://github.com/Codeinwp/shop-isle/blob/production/screenshot.png
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/167#issuecomment-212393783>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by ineagu** [comment]
Issue moved to [Codeinwp/shop-isle-wporg #4](https://github.com/Codeinwp/shop-isle-wporg/issues/4) via [**ZenHub.io**](https://www.zenhub.io/)
