### ISSUE TITLE
Script to not update theme from wp.org

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/shop-isle#178]

**Comment by rodica-andronache** [comment]
@ineagu aici pana la urma a ramas sa mai facem ceva? parca nu

**Comment by ineagu** [comment]
nu

On Wed, May 4, 2016 at 3:12 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> aici pana la urma a ramas sa mai
> facem ceva? parca nu
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/178#issuecomment-216857716>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
