### ISSUE TITLE
Reorganize the frontpage sections in customize

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/shop-isle#187]
into a single panel "Frontpage sections" like on llorix.

@ineagu I did this for the wp.org version ( to also add that section, where we explain how to set up a frontpage) . Should we change this here too?

**Comment by ineagu** [comment]
I think so

On Fri, May 20, 2016 at 1:38 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> into a single panel "Frontpage sections" like on llorix.
>
> @ineagu <https://github.com/ineagu> I did this for the wp.org version (
> to also add that section, where we explain how to set up a frontpage) .
> Should we change this here too?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/187>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
