### ISSUE TITLE
Checkout page issue

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/shop-isle#197]
When writing postal code field, it automatically triggers shipping address checkbox. @rodica-andronache 

Tested on Chrome. Working on FF. The following CSS fixed it by the way:

```.checkbox, .radio {
    display: inline-block !important;
}```

**Comment by rodica-andronache** [comment]
@HardeepAsrani I couldn't relicate this. Could you please make a gif maybe so I can see?

**Comment by HardeepAsrani** [comment]
Will keep an eye. Can't reproduce on my own system.
