### ISSUE TITLE
Shop page layout issue when more products are displayed on one page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/shop-isle#199]
http://prntscr.com/bbecfi

Source: http://themeisle.com/forums/topic/shop-category-pages-empty-spaces-between-products/

To test it, it needs to first change the number of products on shop, with this
http://docs.themeisle.com/article/257-how-to-change-the-number-of-products-on-the-shop-page-in-shopisle

**Comment by claudiuvertistudio** [comment]
@rodica-andronache  I see no problem on localhost.
