### ISSUE TITLE
Changelog looks messy

### ISSUE THREAD

**Issue by balcsida** [Codeinwp/shop-isle#202]
The current CHANGELOG.md file is unreadable after 2.1.7
![image](https://cloud.githubusercontent.com/assets/1768446/15781244/782eda90-29a5-11e6-9730-7b0f354d4aec.png)

**Comment by rodica-andronache** [comment]
Hi @balcsida ,

Thank you very much for contacting us. We are aware of this issue, and it's on our to-do list for the next updates. This happened because we changed the automated process for generating the changelog file.

Regards,
Rodica

**Comment by UVLabs** [comment]
@rodica-andronache please close this :)
