### ISSUE TITLE
Not fully compatible with WC 2.6

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/shop-isle#208]
My account page has no styling done yet: https://woocommerce.wordpress.com/2016/04/21/tabbed-my-account-pages-in-2-6/

@rodica-andronache

**Comment by ineagu** [comment]
Let's monitor wc releases + wp releases and test our products before the release. The support team should be in charge

**Comment by ineagu** [comment]
@rodica-andronache this is important.

**Comment by rodica-andronache** [comment]
https://gist.github.com/Basilakis/4e281c2a8db3447ee9bd2d5a1c924eb0

**Comment by rodica-andronache** [comment]
thanks :dancer:
