### ISSUE TITLE
Compatibility with WooCommerce Products Per Page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/shop-isle#211]
https://wordpress.org/plugins/woocommerce-products-per-page/screenshots/

@ineagu it looks like it only needs some custom css. Can we do this?

Source: http://themeisle.com/forums/topic/more-professional/

**Comment by ineagu** [comment]
yep, if is not big, we can, theme is quite popular

On Tue, Jun 21, 2016 at 3:35 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> https://wordpress.org/plugins/woocommerce-products-per-page/screenshots/
>
> @ineagu <https://github.com/ineagu> it looks like it only needs some
> custom css. Can we do this?
>
> Source: http://themeisle.com/forums/topic/more-professional/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/211>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DHCc660h8HsEGYEwq-aUzfNHDWYsks5qN-ijgaJpZM4I6vW6>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
@claudiuvertistudio can you please test this again? For me it's not working anymore

**Comment by claudiuvertistudio** [comment]
@rodica-andronache I have tested and it works well, perhaps the problem is from Jetpack infinite scroll.
