### ISSUE TITLE
Default latest products on homepage not pulling tax price

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/shop-isle#213]
If the default latest products is kept on the hompage, and tax is added to a product, on the single product page it would show the price including tax but the price on the site's homepage would not reflect this tax price, it shows it without tax. 

If however the shortcode for latest products is used, it does pull the tax.

**Comment by rodica-andronache** [comment]
Hi @UVLabs ,

Can you please help me replicate this? I've never used the tax option in woocommerce and I'm not sure how to replicate it

**Comment by UVLabs** [comment]
Ok i will create a screencast please remind me if I dont send you it by Monday

**Comment by UVLabs** [comment]
@rodica-andronache from this video you could see with the default latest product it does not pull the product with the tax, however when I use the default WC shortcode 

[recent_products per_page="12" columns="4"]

It actually pulls the correct price with tax.

http://youtu.be/6K6lw-O_Ab0?hd=1

**Comment by rodica-andronache** [comment]
@UVLabs thanks but still I couldn't manage to replicate this. Could you please give me some screenshots for what you used in this sections http://prntscr.com/bub6pe?

**Comment by UVLabs** [comment]
@rodica-andronache Only thing I did was set the tax option to " No, I will enter prices exclusive of tax" then set the shop to show the tax: http://prntscr.com/bvqio1

I then went to the standard tax settings and set a tax %: http://prntscr.com/bvqjea

On the product page it shows the correct price: http://prntscr.com/bvqk4e

But in the latest product section it shows the price without tax: http://prntscr.com/bvqjsa

If you use the built in recent products woocommerce shortcode for the latest product section it will show the correct price
