### ISSUE TITLE
Slider Arrow not working on IE or EDGE

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/shop-isle#215]
Slider arrow not as fancy as what's displayed on chrome, instead it's the default resizing arrow @rodica-andronache

**Comment by claudiuvertistudio** [comment]
We can't do anything about this problem beacause Edge/IE doesn't suport cursor url.

**Comment by UVLabs** [comment]
@claudiuvertistudio it looks like you need to specify the full URL for IEs, seems you could add multiple URL Paths for the cursor image property. Have a read of this thread: http://stackoverflow.com/questions/7419314/custom-cursor-image-doesnt-work-in-all-ies

**Comment by claudiuvertistudio** [comment]
Thanks @UVLabs, now it's working.

**Comment by UVLabs** [comment]
No problem @claudiuvertistudio check out my pull request, I'm closing this issue
