### ISSUE TITLE
Mega Menu compatibility

### ISSUE THREAD

**Issue by claudiuvertistudio** [Codeinwp/shop-isle#222]
@ineagu ShopIsle-lite must be compatible with wr-MegaMenu?

**Comment by ineagu** [comment]
not reallly, just if is really easy, we can do it .

On Thu, Jul 7, 2016 at 8:59 AM, Claudiu Buruiana <notifications@github.com>
wrote:

> @ineagu <https://github.com/ineagu> ShopIsle-lite must be compatible with
> wr-MegaMenu?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/222>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DH5ox9QO7cVpHl8kuKu-y-i-ZC-Wks5qTKPVgaJpZM4JGyuX>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by claudiuvertistudio** [comment]
https://github.com/Codeinwp/shop-isle-wporg/commit/d32fc20a46011b23d8c39a92c12801f9e18cc153
