### ISSUE TITLE
Owl Carousel bugs Humbugger menu

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/shop-isle#225]
https://github.com/Codeinwp/islemag/issues/176

**Comment by rodica-andronache** [comment]
@Basilakis we couldn't replicate this. Can you please give more details?
From what I understand you say there is an issue with the hamburger menu when there is just a slide in the main slider right?

**Comment by rodica-andronache** [comment]
@Basilakis you still did not write anything here :) Please don't forget about this

**Comment by Basilakis** [comment]
Rodica fixed that already.
