### ISSUE TITLE
Placeholder image for video on mobile

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/shop-isle#251]
Since autoplay videos aren't available on mobile devices we should be replacing it with an image placeholder which the user sets otherwise it looks weird. @rodica-andronache

**Comment by knireis** [comment]
I am a customer requesting this feature and i would definitely prefer to set my own image in stead of the first video frame. And maybe include an option for a minimum height of the visible part of the image.

**Comment by rodica-andronache** [comment]
same as on pro, can we fix this http://prntscr.com/cfzhy3 ?

**Comment by rodica-andronache** [comment]
Here the variable is not checked if empty before outputing: http://prntscr.com/cia7k2
