### ISSUE TITLE
Submit buttons for forms not showing up

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/shop-isle#258]
https://github.com/Codeinwp/shop-isle-pro/issues/117

**Comment by rodica-andronache** [comment]
@claudiuvertistudio it's not working with this plugin https://wordpress.org/plugins/newsletter/ in the footer. I think we need to have also a different color for the submit buttons in footer, to be visible.

The site address: https://babciaowca.pl/beta/
Newsletter widget is in the footer - the right bottom of the page.
The plugin name: https://wordpress.org/plugins/newsletter/ (but also tried with others)

**Comment by rodica-andronache** [comment]
in footer, the text doesn't seem to be visible. Just in sidebar
