### ISSUE TITLE
hidden products showing up in products section and exclusive slider

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/shop-isle#262]
https://github.com/Codeinwp/shop-isle-pro/issues/107

**Comment by chris-brighton** [comment]
Hi, sorry this problem still persists.

Repro:
1. In wp-admin, create a new product, make it hidden on Catalog. Publish.
2. From browser, go to any other product page, at the bottom, under "Exclusive Products", you wll find the hidden product.

**Comment by rodica-andronache** [comment]
Hi Chris,

Thank you for contacting us. I tried replicated this, but I couldn't see the issue. Could you please  give me your site URL so we can see the issue?

Thank you,
Rodica

**Comment by chris-brighton** [comment]
Hi Rodica,

Is there a way for me to email this to you in private? 

Thanks

**Comment by rodica-andronache** [comment]
Hi Chris,

You can send us an email at friends@themeisle.com. Please mention this issue in the message.

Regards,
Rodica
