### ISSUE TITLE
WooCommerce Stripe Payment Gateway plugin doesn't work

### ISSUE THREAD

**Issue by alexandrastann** [Codeinwp/shop-isle#272]
The continue to payment button doesn't work after the product is added to cart and proceeds with the payment.
When Stripe is selected as payment type for checkout, the button does not work. When you click the 'continue to payment' button, nothing happens.
Error in Console. see attachment 
Website: https://www.shop.yessupply.co/checkout/
![error](https://cloud.githubusercontent.com/assets/12390772/18780994/a6161208-8188-11e6-83ff-08f28020e617.jpg)

**Comment by claudiuvertistudio** [comment]
I have tested and it seems to work well. I think it's not a problem from us.

**Comment by rodica-andronache** [comment]
@alexandrastann yeah, it doesn't seem to be an issue, neither on the user site. Can you also please check again and maybe ask the user if everything is ok now?
