### ISSUE TITLE
Merge Shop Isle , Shop Isle wporg and Shop Isle Pro in one repo

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/shop-isle#308]
# Generate Lite Versions

## Themeisle Lite
- [x] Use Grunt to Generate Lite version from themeisle.com
- [x] Refactor customizer for modularity.
- [x] Move customizer settings for 404 in new panel just in pro version.
- [x] Add powered by to footer in lite
- [x] Fix textdomain
- [x] Change screenshot upon generate

## WP.org Lite
- [x] Use Grunt to Generate Lite version from wp.org
- [x] Replace Big title section
- [x] Customizer Notices

**Comment by abaicus** [comment]
Started here: ff004498ba768491bc64666e12ddabada8724287

**Comment by abaicus** [comment]
Started here: https://github.com/abaicus/shop-isle-pro/commit/ff004498ba768491bc64666e12ddabada8724287

**Comment by abaicus** [comment]
Following features are present in lite version but not in pro: 

![image](https://cloud.githubusercontent.com/assets/15010186/20394838/9459b772-ace9-11e6-9e3e-d694f0243714.png)

![image](https://cloud.githubusercontent.com/assets/15010186/20394863/ad5fe5de-ace9-11e6-8902-dbb66155f64f.png)

What should I do with these? @rodica-andronache

**Comment by abaicus** [comment]
@rodica-andronache @selul I think this is mostly done. You can check it out on [my fork](https://github.com/abaicus/shop-isle-pro/tree/generate).

**Comment by selul** [comment]
@abaicus

 *  i see that wpName and litename are the same in the packages.json, so when we will run grunt generate one will be overwritten by other. it should be different folders even if they are using the same slug, we can try like before wpName : shop-islewprog and shop-isle for lite 

 * i would suggest to not use true/false values for options values, and yes/no values. here for instance: https://github.com/abaicus/shop-isle-pro/blob/generate/inc/init.php#L118 and we should have a default value when running get_option, like get_option( 'shop_isle_section_order_migrate' , 'no'); 

*  https://github.com/abaicus/shop-isle-pro/blob/generate/inc/functions/setup.php#L11 here we should use a constant instead of this, it's much slower to parse the version file each time than storing the value in a constant. for consistency between style.css version and constant value we should use grunt version and update the constant when we update the css version

**Comment by abaicus** [comment]
@selul I think everything is ok now 👍

**Comment by rodica-andronache** [comment]
@abaicus 
ShopIsle wporg 
- titlul apare mai sus http://prnt.sc/dmkpmv si nici shadow-ul ala negru nu mai apare . Cum era inainte http://prnt.sc/dmkpuf.
- copyright si socials din footer ar trebui sa nu aiba valori default, cum era inainte (daca e super complicat, poti lasa cu valori default, dar daca se poate, cred ca ar fi ok sa le scoatem, ca sa nu comenteze cei de la wporg la un moment dat)
- mai erau niste conditii gen https://github.com/Codeinwp/shop-isle-pro/blob/production/inc/sections/shop_isle_video_section.php#L18 ca sa nu apara container-ul de video gol, cand nu e nimic salvat in baza de date http://prntscr.com/dmkwi3
- cand nu e instalat woocommerce , pt admini apareau sane default-urile astea http://prntscr.com/dmkxsq care ar merge puse in toate 3 teme, ca sa fie mai usor, cred si ca sa fie ok si pt cei de la wporg
- link-ul catre documentatie ar trebui sa fie http://docs.themeisle.com/article/421-shop-isle-documentation-wordpress-org daca se poate si ce e acum sa fie shop isle normal.
- Hide big title section nu merge in customizer
- partea asta , cosul care se extinde la hover o avem doar in pro http://prntscr.com/dml7dn
Deocamdata daca le poti rezolva pe astea e ok, si ne mai uitam dupa :)

**Comment by abaicus** [comment]
I think everything is done here. 👍 Can you please take a look @rodica-andronache ?

**Comment by rodica-andronache** [comment]
@abaicus 
Shop Isle Pro:
- logat ca admin http://prnt.sc/doviv6 , nelogat http://prnt.sc/doviq6. Poate ar fi mai ok, ca pe site nelogat, sa nu mai apara Latest products, si nici spatiul ala mare gol?

- logat ca admin http://prnt.sc/dovldf nu ar mai trebui sa apara mesajul ala despre produse, cand sunt produse pe site. Nelogat http://prnt.sc/dovlqd nu apare valoarea default a titlului Exclusive products

- mesajul de la Frontpage settings http://prntscr.com/dovs7q ar trebui sa apara doar pt Shop Isle wporg, pt ca doar acolo e valabila faza cu template-ul de frontpage nu? Si la Shop Isle pro, in caz ca poti pune conditie, ca asta sa apara doar pt cazul in care in s-a facut tranzitia de la shop isle wporg ( complicaciune :D )  . Si ar trebui mutat mesajul, sa nu mai apara intr-o sectiune noua, ci sa fie mesaj in interiorul Frontpage sections , jos de tot, cum e acum la llorix one lite parca.

- In customizer, apare jos de tot un spatiu in plus http://prntscr.com/dovv6d

- Pt Shop Isle de pe ti, nu mi se incarca  customize, nu stiu daca e de la local-ul meu, poti sa incerci si tu

**Comment by abaicus** [comment]
@rodica-andronache 

La 1. cred ca e putin complicat sa scoatem si spatiul gol. Plus ca are din javascript o functie care intinde pagina cu un min-height oricum.

**Comment by abaicus** [comment]
Done! Here it is: https://github.com/abaicus/shop-isle-pro/tree/generate

**Comment by rodica-andronache** [comment]
@abaicus am instalat acum shop isle pro pe un wp nou si nu-mi merge sliderul (apare doar primul slide). La tine merge? La fel si pt shop isle de la noi de pe site

**Comment by abaicus** [comment]
@rodica-andronache Acum ar trebui sa functioneze in regula.

**Comment by rodica-andronache** [comment]
@abaicus 

Cred ca sectiunile din pro la care ai adaugat acum optiunea de scos din tema, ar trebui sa se numeasca tot cum sunt si celelalte Hide... in loc de Disable cum e pus acum.
Background color si background image nu par sa functioneze in Pro, si inaintea mergea ok

La shop isle de la noi de pe site si deci si in pro, nu ar trebui o versiune mai mare decat e acum? adica 2.2.0?

**Comment by abaicus** [comment]
@rodica-andronache Background image si background color functioneaza la fel ca inainte. :D

**Comment by abaicus** [comment]
@rodica-andronache I've replaced the repeater and it works fine with eleganticons. Let me know :D

**Comment by rodica-andronache** [comment]
@abaicus it seems to work fine :) it remains the front-page.php change than, for the wp.org version like in llorix one lite or islemag
- remove the frontpage template
- add the front-page.php file
-filter the frontpage_template https://github.com/Codeinwp/llorix-one-lite/blob/production/functions.php#L667
-add a control in customizer to allow the old settings

Also, for the wp.org version, the social icons in the footer, should not have default values. Right now, there seems to have, even though the ti version has not.

**Comment by rodica-andronache** [comment]
@abaicus in the wporg version, there is still this issue "Also, for the wp.org version, the social icons in the footer, should not have default values. Right now, there seems to have, even though the ti version has not."
-And we should also remove the frontpage template from the theme.
- this message http://prntscr.com/dxkdab should be changed to fit the new structure, without the page template . Also, the check that is done, to check when to display it, should not search for the frontpage template ( I think that's what it does now )

**Comment by rodica-andronache** [comment]
@abaicus am facut aici ceva https://github.com/abaicus/shop-isle-pro/commit/6cc8b0718c60d64ecdba76fa05e4205cb2f95b65 . Mie mi se pare ca merge ok. Mai testezi si tu odata te rog? :)

**Comment by rodica-andronache** [comment]
Fisierul de readme lipseste
Display Site Title and Tagline  nu merge in PRO, cel putin

**Comment by abaicus** [comment]
@rodica-andronache Fisierul de readme e Readme.md. Eu zic ca poate ramane cel din pro si la lite si la wporg. Singura problema ar fi ca are o linie in plus: 

 * ribbon-bg.jpg: https://unsplash.com/photos/VZuLoDocz-U

E o imagine care lipseste din lite-uri. Nu cred ca e neaparat o problema asta. Ce parere ai?

**Comment by abaicus** [comment]
@rodica-andronache Nu stiu ce sa zic de optiunea de display site title and tagline. Ar trebui sa vorbim maine cum vrem sa functioneze exact. Cred ca isi are sensul doar in cazul in care ai un logo pe site. Noi avand setarea ascunsa pana acum, cred ca trebuie sa avem mare grija ce decidem. Ea este true by default si nu o putem face false 
- pentru oamenii care au logo, ar aparea Site Title si Tagline sub logo la update daca nu o facem false; 
- pentru oamenii care nu au logo nu o putem face false pentru ca le-ar disparea Site Title si Tagline.

**Comment by abaicus** [comment]
Alternativ o putem aplica doar in cazul in care nu ai logo si sa o lasam true by default, iar la false sa dispara Site Title si Tagline.

**Comment by rodica-andronache** [comment]
@abaicus pare ok, hai sa vb maine de versionare si sa o punem :)
