### ISSUE TITLE
Welcome page + customizer setup

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/shop-isle#317]
@rodica-andronache @abaicus after we succesfully connect the 3 repos we can work on the onboarding process which is really bad now, few things : 

- add the welcome page with recommended/required actions ( recommend nivo + frontpage setup)
- move all customizer settings under one panel : theme options ( except theme-info ) one .
- remove front-page settings.
- we can find a better way to show that info box in the frontpage sections part.

The design for theme-info + other small upsells can be better, for example check : NewsMag .

**Comment by piet638** [comment]
Great news, thanks a lot for all your work. Can I hope to switch to something like Font Awesome in next update ?

**Comment by rodica-andronache** [comment]
Hi @piet638 ,

I'm not sure if we can switch all the fonts in the theme, considering that users usually create child themes, and we don't want to break them, but we'll definitely try to somehow incorporate Font Awesome in the theme in the future.

Thanks,
Rodica
