### ISSUE TITLE
remove the need to select a frontpage template for NEW USERS on w.org vers

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/shop-isle#319]
cc @abaicus @rodica-andronache

**Comment by rodica-andronache** [comment]
@abaicus I think we could do this, before merging the repos, to be easier. What do you think?

- remove the frontpage template
- add the front-page.php file
- filter the frontpage_template https://github.com/Codeinwp/llorix-one-lite/blob/production/functions.php#L667
- add a control in customizer to allow the old settings
