### ISSUE TITLE
Issue with upsells on single product page

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/shop-isle#325]
@rodica-andronache on single product page it shows 3 products per row instead of 4, the 4th one goes on the bottom of it: http://prntscr.com/e4mq6w

Happens on normal laptop 1366px

**Comment by rodica-andronache** [comment]
@UVLabs please don't add issues here anymore. add them here https://github.com/Codeinwp/shop-isle-pro/ with mention, for which theme it is
