### ISSUE TITLE
[feature request] Out of stock badge

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/shop-isle#327]
@rodica-andronache similar to sale badge or at least maybe with a colored background

**Comment by rodica-andronache** [comment]
@UVLabs please don't post issues here . all 3 shop isle themes are generated from here https://github.com/Codeinwp/shop-isle-pro/. you can check the description of the repo http://prntscr.com/ek801i

**Comment by UVLabs** [comment]
Ok cool sorry, saw the message on the shopisle wp.org repo this one didn't have it
