### ISSUE TITLE
Single product page lightbox issue

### ISSUE THREAD

**Issue by mohdshakeel** [Codeinwp/shop-isle#328]
Hi,
@rodica-andronache - Single product page  images are not opening with lightbox after new update of Woocommerce 3.0.0. When i click on image, it opens in browser tab as URL instead of lightbox like demo.

I have added few code at functions.php of theme to resolve the issue.
**add_theme_support( 'wc-product-gallery-zoom' );
add_theme_support( 'wc-product-gallery-lightbox' );
add_theme_support( 'wc-product-gallery-slider' );**

After adding this code, I got fix the issue but lightbox open in new style with full screen view and close icons at top right corner . I have attached three images to explain the issue better. 
![lighbox-issue-3](https://cloud.githubusercontent.com/assets/1772444/24751199/43c22482-1ae6-11e7-90fe-e987def150a4.png)

![lightbox-issue-1](https://cloud.githubusercontent.com/assets/1772444/24751083/e1114bf6-1ae5-11e7-9ecb-09465f59e0e1.png)
![lightbox-issue-2](https://cloud.githubusercontent.com/assets/1772444/24751165/2c968b5e-1ae6-11e7-8566-10a618a6edff.png)

**Comment by rodica-andronache** [comment]
this was fixed
