### ISSUE TITLE
Can't add link in the Copyright

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/shop-isle#332]
http://prntscr.com/f13pyx

Other themes allow to add link in the copyright field.

**Comment by rodica-andronache** [comment]
@stefan-cotitosu this repo will be deleted eventually as we merged all 3 shop isle versions in here https://github.com/Codeinwp/shop-isle-pro, so all issues related to shop isle, no matter which version, you can add them there. If the issue is just for one of them, you can mention there.
