### ISSUE TITLE
Product slider Messed up in mobile view

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/shop-isle#333]
@rodica-andronache Font page product slider section is not looking good in mobile view. The products become too small and show very closely.

**Comment by rodica-andronache** [comment]
@poonam279 I will close this issue here, as all shop isle version are generated from here https://github.com/Codeinwp/shop-isle-pro and we'll fix it there :)

**Comment by Hard-One** [comment]
@rodica-andronache You should consider making the issue tracker public ;) Your link returns a 404 since it is a private repo...
