### ISSUE TITLE
Breadcrumbs issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/shop-isle#339]
@rodica-andronache I have tried to add Breadcrumbs using our doc http://docs.themeisle.com/article/383-how-to-add-breadcrumb-navigation-to-your-theme and doesn't work. 

Tried to do it on a default theme and works. Can you please check it?

**Comment by rodica-andronache** [comment]
@mileamadalin it's working, you probably added it just after the div with the main class, but not all themes have the same structure. For shop isle, for example, you have to add it a bit lower in the file, inside the div with container class.
Let me know if you meant something else.
And please add all the issue for both Shop Isle and Shop Isle PRO in the shop-isle-pro repository, as we generate the lite theme from there too. When posting in a repo, you can check the description https://prnt.sc/i5xif8 , this repo will be deleted
