### ISSUE TITLE
A little layout bug at archive page's sidebar

### ISSUE THREAD

**Issue by quwahiro** [Codeinwp/shop-isle#340]
Hi 

Thanks good template. I love it :)

So, I found a little bug at archive page (shop page).
When the breadcrumb is short (likely "/home/shop" ) , then the sidebar down.
I added min-width:16em in ".module-small-shop .woocommerce-breadcrumb{}".

Sincerely

**Comment by rodica-andronache** [comment]
Hi @quwahiro,
Thank you for contacting us, we are really happy to hear you enjoy our theme.
Regarding the issue with the breadcrumbs maybe you could mention your site so I can see the issue?  On our demo it seems to be ok https://demo.themeisle.com/shop-isle/shop/
Regards,
Rodica

**Comment by quwahiro** [comment]
Hi Rodica san,

Thank you information :)

yes, I saw this demo page. so that the first,I didn't guess breadcrumbs place.
and I checked js,css and so on. there wasn't problem.
next ,The other archive page  displayed right.
I checked  other archive with chrome dev mode.
and I noticed to different width of breadcrumbs.
I tried to add dummy in this breadcrumbs line. (likely, home/shopaaaaa...)
and The sidebar could fit left.

my site is "https://napier.jp/shop/"

![image](https://user-images.githubusercontent.com/746995/35970290-282c90da-0d0d-11e8-9a10-b097c255abfb.png)

Please try untick checkbox of "min-height".
Safari could display right. but Chrome couldn't it.
It occur over 1200px (min-width: 1200px).
I maybe guess font problem.

and There are other informations.
When I'm searching about this problem, I found it.
line 412,489's are too many div
![image](https://user-images.githubusercontent.com/746995/35970462-c09643c0-0d0d-11e8-8a70-732d2ac47c86.png)
I help to debug this problem :)
If I can find it, I pull request this repo.

Regards,
Hiro

**Comment by rodica-andronache** [comment]
Hi @quwahiro ,

Thank you for the details but unfortunately, I couldn't understand exactly what the problem is. I'm not sure if you say the problem is only on your site and not on the demo? Can you show me a screenshot of the problem?

Thank you,
Rodica

**Comment by quwahiro** [comment]
Hi Rodica san,

Ah ok, I try to install and to test from basic data at the begining.

thanks.

**Comment by rodica-andronache** [comment]
Ok, let me know if you manage to get a screenshot of the exact problem.

Thanks

**Comment by quwahiro** [comment]
Rodica san

it is ok :) thanks your help :)
because, I was going to wrote How to reproduce it, in order to no need screen shot and to contribute for this theme.
but my english ability was poor, so that You didn't try to reproduce.

Pls close this ticket.
thanks :)
