### ISSUE TITLE
Products in Shop page not clickable in Mobile 

### ISSUE THREAD

**Issue by mrcldigital** [Codeinwp/shop-isle#341]
It seems that the woocommerce-pagination is blocking the whole page on mobile that's why products are not clickable

Please check

**Comment by rodica-andronache** [comment]
Hi @mrcldigital ,

Thank you for contacting us! Could you please share more details here, like your site URL, what version of the theme and WooCommerce are you using?

@stefan-cotitosu meanwhile could you please test on your side and see if you can replicate this? ( With the generated theme, from the shop-isle-pro theme )

**Comment by rodica-andronache** [comment]
Hi @mrcldigital ,

We figured out the problem and we'll release an update in the next days.

Thank you,
Rodica
