### ISSUE TITLE
Demo checkout page is blank

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/shop-isle#342]
If we access checkout page from iFrame - https://themeisle.com/demo/?theme=ShopIsle%20Pro, it gives blank page.

There is an error in console: http://prntscr.com/jg31mp.

If we open it directly, it works: https://demo.themeisle.com/shop-isle-pro/checkout/

@rodica-andronache

**Comment by rodica-andronache** [comment]
@Vishakha-Patel thanks 👍 it's already here https://github.com/Codeinwp/themeisle/issues/470 not sure how to fix it :(
