### ISSUE TITLE
Upgrade to pro and upsells

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/shop-isle#86]

**Comment by rodica-andronache** [comment]
@ineagu aici punem upsells si la varianta de pe wp.org si cea de la noi? ca nu mai stiu, parca vorbisem sa nu mai punem la una, dar nu mai stiu daca shop isle era.
Si daca punem, punem doar button de view pro si pt cea de pe wp.org leave us a review  ca la oblique ? http://prntscr.com/ba7vyd ca sa nu fie stringuri netraduse la cea de pe wp.org

**Comment by ineagu** [comment]
1, Punem upsell doar pe cea de la noi

On Mon, May 30, 2016 at 5:00 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> aici punem upsells si la varianta de
> pe wp.org si cea de la noi? ca nu mai stiu, parca vorbisem sa nu mai
> punem la una, dar nu mai stiu daca shop isle era.
> Si daca punem, punem doar button de view pro si pt cea de pe wp.org leave
> us a review ca la oblique ? http://prntscr.com/ba7vyd ca sa nu fie
> stringuri netraduse la cea de pe wp.org
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/86#issuecomment-222510062>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DCPHTnlKxT5jrqP6TkYuXTalX91Qks5qGvuJgaJpZM4G5FIe>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
Fixed in this commit https://github.com/Codeinwp/shop-isle/commit/f85b2546c150d278374b6d280a250fcd4da231f5

**Comment by ineagu** [comment]
si ceva panels aici :P

On Tue, May 31, 2016 at 11:34 AM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> am pus doar button. Vrei sa incercam
> doar asa acum? sau punem si cateva panel-uri cu ce are in pro?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/shop-isle/issues/86#issuecomment-222639011>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DK_YNOARwKX2wxH_RT1C-HeF94bnks5qHACOgaJpZM4G5FIe>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
